{
  "hash": "2aa585e272c4f165265b3cf285478980",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Joining Data\ndescription: 'How to merge your data!\n\n  '\ncreative_commons: CC BY\n---\n\n\n\n\n\n\n:::obj\n\n**Joining Data**\n \n - Understand different types of joins and how to use them\n - Understand how to join datasets by shared data columns\n - Join data with different variable names\n\n:::\n\n## Joining Data\n\nWe often need to take several datasets and merge them into a single dataset that we can use for analysis. This \"**join**\" can at times be tricky, and can be made more so if we aren't exactly sure what data matches up between the two datasets, or if the same data is named differently in each dataframe. Sometimes joining data can resemble more of a gridlock than a clean and seamless merge.\n\n(ref:gridlockWiki) Merging Data? *(source Wikipedia Commons)*\n\n<center>\n\n\n\n::: {.cell preview='true'}\n::: {.cell-output-display}\n![(ref:gridlockWiki)](images/New_York_City_Gridlock.jpeg){width=384 height=50%}\n:::\n:::\n\n\n\n</center>\n\n### Common Variables\n\nThe trick that makes a join possible is to have one or more shared variables across each dataset. This may be an ID column, or a specific [data class](m_data_structures.qmd#basic-object-classes). Importantly, these data can actually have different column names, but typically each needs to have the same *class* of data (i.e., `character` and `character`) and some shared observations across each dataset in order to **join** the datasets.\n\nWhile this may seem daunting at first, it's not! R has some excellent tools built into the **`{dplyr}`** package that make joining datasets fairly straightforward. First let's import some data we can use to join. Here we will build off of the datasets we used in the [previous {dplyr} module](m_dplyr.qmd). \n\nFirst let's load the libraries and data we'll be using. We'll be continuing to use some groundwater data as shown in previous modules, including a dataframe of **`stations`**, **`measurements`** through time, and information on **`perforations`**. We'll also *join* these data to the [CalEnviroscreen dataset](https://oehha.ca.gov/calenviroscreen) which \"*identifies California communities by census tract that are disproportionately burdened by, and vulnerable to, multiple sources of pollution*\". One of the most notable uses of the CalEnviroscreen dataset has been to inform CalEPA’s identification of disadvantaged communities. We'll be using CalEnviroscreen v3.0 in the code that follows.\n\n\n\n\n::: {.cell messages='false'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n# GW stations data\ngw_stations <- read_csv(\"data/gwl/stations.csv\")\n\n# GW measurements data for Sac, El Dorado, Placer Counties\ngw_measurements <- read_csv(\"data/gwl/measurements_sep.csv\")\n\n# GW depths\ngw_perf <- read_csv(\"data/gwl/perforations.csv\")\n\n# CalEnviroscreen Data\ncalenviro <- read_csv(\"data/calenviroscreen/ces3results_data.csv.zip\")\n```\n:::\n\n\n\n\n<aside>\n\nDid you know you can read a `.zip` file directly with `read_csv()`? Saves disk space \n\n</aside>\n\n<br>\n\n:::challenge\n\n<font color=\"#009E73\">**Challenge 1: Find the Commonalities**</font> \n\n - Look at the 3 different groundwater datasets (`gw_measurments`, `gw_perf`, and `gw_stations`) and find potential common columns/variables we can use to join. How many are there?\n \n:::\n\n\n<details>\n  <summary class=\"challenge-ans-title\">**Click for Answers!**</summary>\n  <div class=\"challenge-ans-body\">\n\nThere are many ways to view our data. We want to not only know the column names, but also what kind of data exists in each. What common columns can we use?\n\n - **`SITE_CODE`** and **`STN_ID`** is in each of the `gw_measurments`, `gw_perf`, and `gw_stations` datasets.\n \nA great package to use for cleaning and checking things like this is the {[`janitor`](http://sfirke.github.io/janitor/)} package. We can use the `compare_df_cols` function to find out what data types exist across the dataframes we want to potentially join.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)\n# tells us the column class in each dataframe, NA's for non-existent cols\ncompare_df_cols(gw_stations, gw_perf, gw_measurements)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"column_name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"gw_stations\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"gw_perf\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"gw_measurements\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"BASIN_CODE\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"BASIN_NAME\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"BOT_PRF\",\"2\":\"NA\",\"3\":\"numeric\",\"4\":\"NA\"},{\"1\":\"COOP_AGENCY_ORG_ID\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"COOP_ORG_NAME\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"character\"},{\"1\":\"COUNTY_NAME\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"GSE_WSE\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"LATITUDE\",\"2\":\"numeric\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"LONGITUDE\",\"2\":\"numeric\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"MSMT_CMT\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"character\"},{\"1\":\"MSMT_DATE\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"POSIXct, POSIXt\"},{\"1\":\"RDNG_RP\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"RDNG_WS\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"RPE_WSE\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"SITE_CODE\",\"2\":\"character\",\"3\":\"character\",\"4\":\"character\"},{\"1\":\"STN_ID\",\"2\":\"numeric\",\"3\":\"numeric\",\"4\":\"numeric\"},{\"1\":\"SWN\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"TOP_PRF\",\"2\":\"NA\",\"3\":\"numeric\",\"4\":\"NA\"},{\"1\":\"WCR_NO\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"WELL_DEPTH\",\"2\":\"numeric\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"WELL_NAME\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"WELL_TYPE\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"WELL_USE\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"WLM_ACC\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"WLM_ACC_DESC\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"character\"},{\"1\":\"WLM_DESC\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"character\"},{\"1\":\"WLM_GSE\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"WLM_ID\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"WLM_METHOD\",\"2\":\"character\",\"3\":\"NA\",\"4\":\"NA\"},{\"1\":\"WLM_ORG_ID\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"WLM_ORG_NAME\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"character\"},{\"1\":\"WLM_QA_DESC\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"character\"},{\"1\":\"WLM_RPE\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"},{\"1\":\"WSE\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"numeric\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# note SITE_CODE and STN_ID both exist across all 3 datasets\n```\n:::\n\n\n\n\n  </div>\n</details> \n\n\n### Same Data, Different Names\n\nNow we'd like to know if there are similar data columns between the groundwater datasets and the CalEnviroscreen data. To do this let's inspect our `stations` and `calenviro` data with either `head` or `names` or `str`. All will tell us similar information. At this point, we know we can tie the groundwater data together, but we need to find something to crosswalk or join the CalEnviroscreen data to the groundwater data. In this case, the CalEnviroscreen data are at a census tract level, and contain data with ZIP codes, counties, and census tracts.\n\n(ref:AHmeetdata) *Artwork by @allison_horst*\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![(ref:AHmeetdata)](https://raw.githubusercontent.com/allisonhorst/stats-illustrations/master/make-your-own-stats-cartoons/ex_2.png){width=80%}\n:::\n:::\n\n\n\n\nThere are a lot of variables in the CalEnviroscreen dataset, so we're only showing the first 10 here.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(calenviro) %>% head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Census Tract\"                                     \n [2] \"Total Population\"                                 \n [3] \"California County\"                                \n [4] \"ZIP\"                                              \n [5] \"Nearby City \\n(to help approximate location only)\"\n [6] \"Longitude\"                                        \n [7] \"Latitude\"                                         \n [8] \"CES 3.0 Score\"                                    \n [9] \"CES 3.0 Percentile\"                               \n[10] \"CES 3.0 \\nPercentile Range\"                       \n```\n\n\n:::\n\n```{.r .cell-code}\nnames(gw_stations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"STN_ID\"      \"SITE_CODE\"   \"SWN\"         \"WELL_NAME\"   \"LATITUDE\"   \n [6] \"LONGITUDE\"   \"WLM_METHOD\"  \"WLM_ACC\"     \"BASIN_CODE\"  \"BASIN_NAME\" \n[11] \"COUNTY_NAME\" \"WELL_DEPTH\"  \"WELL_USE\"    \"WELL_TYPE\"   \"WCR_NO\"     \n```\n\n\n:::\n:::\n\n\n\n\nWhat do we see? Looks like we have county names in both of these datasets, but they have different column names (*`COUNTY_NAME`* in `stations` and *`California County`* in `calenviro`. So we know we can join our three groundwater datasets together, and we know we can join the CalEnviroscreen data with the `stations` dataset by county. Let's talk about the types of joins we may use now!\n\n## Join Types\n\nThere are quite a few different join types that are available via the **{dplyr}** package. Here are some great animations by [Garrick Aden-Buie](https://www.garrickadenbuie.com/project/tidyexplain/#usage) that help illustrate the various join types. \n\n### Left Join\n\nReturns all rows from `x`, and all columns from `x` and `y`. Rows in `x` with no match in `y` will have `NA` values in the new columns. Probably one of the most common joins, where we want to keep *everything* from our first dataframe (`x`), and anything that matches `x` from the second dataframe (`y`).\n\n<aside>\nThe left join is perhaps the most commonly used join, and if you only know one join, this should be it. \n</aside>\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/left-join.gif){width=70%}\n:::\n:::\n\n\n\n\n### Inner Join\n\nThe matching join, returns all rows from `x` where there are matching values in `y`, and all columns from `x` and `y`.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/inner-join.gif){width=70%}\n:::\n:::\n\n\n\n\n\n### Full Join\n\nReturns all rows and all columns from both `x` and `y`. Where there are not matching values, the function returns `NA` for that observation. This is a full merge, where no data is lost from either dataset, and any non-matching data gets an `NA`.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/full-join.gif){width=70%}\n:::\n:::\n\n\n\n\n### Semi Join\n\nReturns all rows from `x` where there are matching values in `y`, keeping only columns from `x`. Also known as a *filtering join* because you are basically filtering one dataframe, using another dataframe as the match. This can be useful when you don't actually want to join with data, but you do want to subset the data to match observations in another dataset.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/semi-join.gif){width=70%}\n:::\n:::\n\n\n\n\n\n### Anti Join\n\nAlso a *filtering join*. This keeps all rows from `x` where there are not matching values in `y`, keeping just columns from `x`. This join is useful to find out which data is **not** joining. Note, the dataframe you put first matters: if you switch `x` and `y` you may get different answers.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/anti-join.gif){width=70%}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n## Joining With Common Variable Names\n\nLet's demonstrate some joins with our groundwater dataframes. First, we'll **`filter`** the station data to only stations in Sacramento County, and then join these data with the other groundwater data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsac_stations <- gw_stations %>% \n  filter(COUNTY_NAME == \"Sacramento\")\n\ndim(sac_stations) # get number of ROWS , COLUMNS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 494  15\n```\n\n\n:::\n:::\n\n\n\n\nIt looks like we have 494 groundwater stations in Sacramento County. Let's use this subset of data to join to our other groundwater dataframes.\n\n### Using the defaults\n\nThe various `joins` outlined above are very flexible, but the default options are also very good. That means, if we don't specify any details, the functions will often try to match and join based on common columns (that have identical names and data types), though this isn't a great habit to set because that may not always be what we want 👾!\n\nLet's **`left_join()`** our Sacramento stations with the `gw_measurments` data. Note, we expect to get the same number of stations as the *left* part of our join (the `x` data.frame), because `left_join` should keep everything on the left side, and only keep what matches from the right side (`y`).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# default join, only give x, y\nsac_stations_measurements <- left_join(sac_stations, gw_measurements)\n\ndim(sac_stations_measurements)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28208    32\n```\n\n\n:::\n:::\n\n\n\n\nWhat happened? Since there are two matching columns, the join used both `STN_ID` and `SITE_CODE`. We ended up with *lots* more observations, and additional columns. It's important to check and validate things worked.\n\n:::challenge\n\n<font color=\"#009E73\">**Challenge 2: Verify the Join**</font> \n\n - How can we verify we successfully joined our two datasets? \n - Can you use either `unique()` or `distinct()` to prove we only have groundwater stations from Sacramento County in our joined dataset?\n \n:::\n\n<details>\n  <summary class=\"challenge-ans-title\">**Click for Answers!**</summary>\n  <div class=\"challenge-ans-body\">\n\nIt's always a good idea to double check both visually and numerically that things are working as expected. In the example above, there are many `gw_measurements` per station so it may seem difficult to know this worked. However, we can double check the number of unique stations in our joined dataset...it should still equal the total number stations in our `sac_stations` dataset (n = 494).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# look at how many unique SITE_CODE are in orig sac only dataset\ndistinct(sac_stations, SITE_CODE) %>% nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 494\n```\n\n\n:::\n\n```{.r .cell-code}\n# look at how many unique are in joined dataset\ndistinct(sac_stations_measurements, SITE_CODE) %>% nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 494\n```\n\n\n:::\n\n```{.r .cell-code}\n# look at top 10 stations with the most measurements:\nsac_stations_measurements %>% \n  group_by(SITE_CODE) %>% # group by SITE_CODE\n  tally() %>% # count how many measurements by STATION\n  arrange(desc(n)) %>% # arrange by count (n), descending\n  head(10) # top 10 records only\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"SITE_CODE\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"384121N1212102W001\",\"2\":\"1582\"},{\"1\":\"383264N1213191W001\",\"2\":\"642\"},{\"1\":\"382548N1212908W001\",\"2\":\"595\"},{\"1\":\"384082N1213845W001\",\"2\":\"541\"},{\"1\":\"385567N1214751W001\",\"2\":\"510\"},{\"1\":\"386016N1213761W001\",\"2\":\"508\"},{\"1\":\"383204N1214430W001\",\"2\":\"499\"},{\"1\":\"384403N1212921W001\",\"2\":\"358\"},{\"1\":\"386151N1214467W001\",\"2\":\"321\"},{\"1\":\"384147N1214507W001\",\"2\":\"311\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\n  </div>\n</details>\n\nIf we use an `inner_join()`, do we get a different number of stations? Why?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# default join, only give x, y\nsac_stations_inner <- inner_join(sac_stations, gw_measurements)\n\n# check station number\ndistinct(sac_stations_inner, SITE_CODE) %>% nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 420\n```\n\n\n:::\n:::\n\n\n\n\nThere's a different number of stations here! What happened? Remember, `inner_join()` only keeps the *rows that match in both data frames*. So, this means while the original `sac_stations` dataset had 494 stations, the `gw_measurements` dataset does not have data for every station in the `sac_stations` dataset, thus `n = 420` instead `n = 494`. When using `left_join()`, these missing observations get filled with `NA`, whereas with `inner_join()`, they are dropped.\n\n### Piping Joins\n\nWe saw how we can join two datasets, but let's try piping these together so we can join all three groundwater datasets together in one single chain of code. We'll start with our Sacramento County stations only. \n\nHere we'll pipe the data to the function, which means we only need to add the `y` argument. In R, a \"`.`\" is like a placeholder that represents the data we are piping along. It's not strictly required (try running the function without it!), but here it helps us see the pieces that go into the function (`x` and `y`).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# note, we aren't specifying the columns we want to join on (keep defaults)\nsac_gw_data_joined <- sac_stations %>% \n  left_join(., gw_measurements) %>% # passing this result to the next join\n  left_join(., gw_perf)\n\n# quick check of stations, should be n=494, because left_join!\ndistinct(sac_gw_data_joined, SITE_CODE) %>% nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 494\n```\n\n\n:::\n:::\n\n\n\n\n\n## Joining With Different Variable Names\n\nWhat about joining dataframes with different variable names? This is much more common when trying to merge different datasets. Let's try to join the CalEnviroscreen data with the Sacramento County groundwater `stations` data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalenviro_stations <- left_join(calenviro, sac_stations)\n```\n:::\n\n\n\n\n```\nError: `by` must be supplied when `x` and `y` have no common variables.\nℹ use by = character()` to perform a cross-join.\nRun `rlang::last_error()` to see where the error occurred.\n```\n\n(ref:facewiggle) *Artwork by @allison_horst*\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![(ref:facewiggle)](images/faces_squiggle.png){width=448 height=2%}\n:::\n:::\n\n\n\n\nUh-oh, an error message! But if we look more closely, this error message is pretty descriptive. It tells us the two pieces we are working with (x = `calenviro` and y = `sac_stations`) don't have a common variable name. Then it gives us a suggestion, `use by = character()`. Let's try specifying the column names we want to join using the **`by`** argument. Note, we need to quote the variable names here (a `character()` vector), and they need to match the same order the dataframes were provided (`x` and `y`).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalenviro_stations <- inner_join(sac_stations, calenviro,\n                                by = c(\"COUNTY_NAME\" = \"California County\"))\n\ndim(calenviro_stations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 156598     71\n```\n\n\n:::\n:::\n\n\n\n\nGreat this worked! But let's figure out why there are so many records if there were only n = 494 stations.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# how many stations per census tract?\ncalenviro_stations %>% count(`Census Tract`)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Census Tract\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"6067000100\",\"2\":\"494\"},{\"1\":\"6067000200\",\"2\":\"494\"},{\"1\":\"6067000300\",\"2\":\"494\"},{\"1\":\"6067000400\",\"2\":\"494\"},{\"1\":\"6067000500\",\"2\":\"494\"},{\"1\":\"6067000600\",\"2\":\"494\"},{\"1\":\"6067000700\",\"2\":\"494\"},{\"1\":\"6067000800\",\"2\":\"494\"},{\"1\":\"6067001101\",\"2\":\"494\"},{\"1\":\"6067001200\",\"2\":\"494\"},{\"1\":\"6067001300\",\"2\":\"494\"},{\"1\":\"6067001400\",\"2\":\"494\"},{\"1\":\"6067001500\",\"2\":\"494\"},{\"1\":\"6067001600\",\"2\":\"494\"},{\"1\":\"6067001700\",\"2\":\"494\"},{\"1\":\"6067001800\",\"2\":\"494\"},{\"1\":\"6067001900\",\"2\":\"494\"},{\"1\":\"6067002000\",\"2\":\"494\"},{\"1\":\"6067002100\",\"2\":\"494\"},{\"1\":\"6067002200\",\"2\":\"494\"},{\"1\":\"6067002300\",\"2\":\"494\"},{\"1\":\"6067002400\",\"2\":\"494\"},{\"1\":\"6067002500\",\"2\":\"494\"},{\"1\":\"6067002600\",\"2\":\"494\"},{\"1\":\"6067002700\",\"2\":\"494\"},{\"1\":\"6067002800\",\"2\":\"494\"},{\"1\":\"6067002900\",\"2\":\"494\"},{\"1\":\"6067003000\",\"2\":\"494\"},{\"1\":\"6067003101\",\"2\":\"494\"},{\"1\":\"6067003102\",\"2\":\"494\"},{\"1\":\"6067003202\",\"2\":\"494\"},{\"1\":\"6067003203\",\"2\":\"494\"},{\"1\":\"6067003204\",\"2\":\"494\"},{\"1\":\"6067003300\",\"2\":\"494\"},{\"1\":\"6067003400\",\"2\":\"494\"},{\"1\":\"6067003501\",\"2\":\"494\"},{\"1\":\"6067003502\",\"2\":\"494\"},{\"1\":\"6067003600\",\"2\":\"494\"},{\"1\":\"6067003700\",\"2\":\"494\"},{\"1\":\"6067003800\",\"2\":\"494\"},{\"1\":\"6067003900\",\"2\":\"494\"},{\"1\":\"6067004001\",\"2\":\"494\"},{\"1\":\"6067004004\",\"2\":\"494\"},{\"1\":\"6067004005\",\"2\":\"494\"},{\"1\":\"6067004006\",\"2\":\"494\"},{\"1\":\"6067004008\",\"2\":\"494\"},{\"1\":\"6067004009\",\"2\":\"494\"},{\"1\":\"6067004010\",\"2\":\"494\"},{\"1\":\"6067004011\",\"2\":\"494\"},{\"1\":\"6067004012\",\"2\":\"494\"},{\"1\":\"6067004100\",\"2\":\"494\"},{\"1\":\"6067004201\",\"2\":\"494\"},{\"1\":\"6067004202\",\"2\":\"494\"},{\"1\":\"6067004203\",\"2\":\"494\"},{\"1\":\"6067004300\",\"2\":\"494\"},{\"1\":\"6067004401\",\"2\":\"494\"},{\"1\":\"6067004402\",\"2\":\"494\"},{\"1\":\"6067004501\",\"2\":\"494\"},{\"1\":\"6067004502\",\"2\":\"494\"},{\"1\":\"6067004601\",\"2\":\"494\"},{\"1\":\"6067004602\",\"2\":\"494\"},{\"1\":\"6067004701\",\"2\":\"494\"},{\"1\":\"6067004702\",\"2\":\"494\"},{\"1\":\"6067004801\",\"2\":\"494\"},{\"1\":\"6067004802\",\"2\":\"494\"},{\"1\":\"6067004903\",\"2\":\"494\"},{\"1\":\"6067004904\",\"2\":\"494\"},{\"1\":\"6067004905\",\"2\":\"494\"},{\"1\":\"6067004906\",\"2\":\"494\"},{\"1\":\"6067005001\",\"2\":\"494\"},{\"1\":\"6067005002\",\"2\":\"494\"},{\"1\":\"6067005101\",\"2\":\"494\"},{\"1\":\"6067005102\",\"2\":\"494\"},{\"1\":\"6067005201\",\"2\":\"494\"},{\"1\":\"6067005202\",\"2\":\"494\"},{\"1\":\"6067005204\",\"2\":\"494\"},{\"1\":\"6067005205\",\"2\":\"494\"},{\"1\":\"6067005301\",\"2\":\"494\"},{\"1\":\"6067005402\",\"2\":\"494\"},{\"1\":\"6067005403\",\"2\":\"494\"},{\"1\":\"6067005404\",\"2\":\"494\"},{\"1\":\"6067005502\",\"2\":\"494\"},{\"1\":\"6067005505\",\"2\":\"494\"},{\"1\":\"6067005506\",\"2\":\"494\"},{\"1\":\"6067005508\",\"2\":\"494\"},{\"1\":\"6067005509\",\"2\":\"494\"},{\"1\":\"6067005510\",\"2\":\"494\"},{\"1\":\"6067005601\",\"2\":\"494\"},{\"1\":\"6067005605\",\"2\":\"494\"},{\"1\":\"6067005606\",\"2\":\"494\"},{\"1\":\"6067005701\",\"2\":\"494\"},{\"1\":\"6067005702\",\"2\":\"494\"},{\"1\":\"6067005801\",\"2\":\"494\"},{\"1\":\"6067005803\",\"2\":\"494\"},{\"1\":\"6067005804\",\"2\":\"494\"},{\"1\":\"6067005901\",\"2\":\"494\"},{\"1\":\"6067005903\",\"2\":\"494\"},{\"1\":\"6067005904\",\"2\":\"494\"},{\"1\":\"6067006002\",\"2\":\"494\"},{\"1\":\"6067006003\",\"2\":\"494\"},{\"1\":\"6067006004\",\"2\":\"494\"},{\"1\":\"6067006101\",\"2\":\"494\"},{\"1\":\"6067006102\",\"2\":\"494\"},{\"1\":\"6067006201\",\"2\":\"494\"},{\"1\":\"6067006202\",\"2\":\"494\"},{\"1\":\"6067006300\",\"2\":\"494\"},{\"1\":\"6067006400\",\"2\":\"494\"},{\"1\":\"6067006500\",\"2\":\"494\"},{\"1\":\"6067006600\",\"2\":\"494\"},{\"1\":\"6067006701\",\"2\":\"494\"},{\"1\":\"6067006702\",\"2\":\"494\"},{\"1\":\"6067006800\",\"2\":\"494\"},{\"1\":\"6067006900\",\"2\":\"494\"},{\"1\":\"6067007001\",\"2\":\"494\"},{\"1\":\"6067007004\",\"2\":\"494\"},{\"1\":\"6067007007\",\"2\":\"494\"},{\"1\":\"6067007010\",\"2\":\"494\"},{\"1\":\"6067007011\",\"2\":\"494\"},{\"1\":\"6067007012\",\"2\":\"494\"},{\"1\":\"6067007013\",\"2\":\"494\"},{\"1\":\"6067007014\",\"2\":\"494\"},{\"1\":\"6067007015\",\"2\":\"494\"},{\"1\":\"6067007016\",\"2\":\"494\"},{\"1\":\"6067007017\",\"2\":\"494\"},{\"1\":\"6067007018\",\"2\":\"494\"},{\"1\":\"6067007019\",\"2\":\"494\"},{\"1\":\"6067007020\",\"2\":\"494\"},{\"1\":\"6067007101\",\"2\":\"494\"},{\"1\":\"6067007102\",\"2\":\"494\"},{\"1\":\"6067007103\",\"2\":\"494\"},{\"1\":\"6067007104\",\"2\":\"494\"},{\"1\":\"6067007105\",\"2\":\"494\"},{\"1\":\"6067007106\",\"2\":\"494\"},{\"1\":\"6067007107\",\"2\":\"494\"},{\"1\":\"6067007202\",\"2\":\"494\"},{\"1\":\"6067007204\",\"2\":\"494\"},{\"1\":\"6067007206\",\"2\":\"494\"},{\"1\":\"6067007207\",\"2\":\"494\"},{\"1\":\"6067007208\",\"2\":\"494\"},{\"1\":\"6067007209\",\"2\":\"494\"},{\"1\":\"6067007301\",\"2\":\"494\"},{\"1\":\"6067007402\",\"2\":\"494\"},{\"1\":\"6067007403\",\"2\":\"494\"},{\"1\":\"6067007406\",\"2\":\"494\"},{\"1\":\"6067007413\",\"2\":\"494\"},{\"1\":\"6067007414\",\"2\":\"494\"},{\"1\":\"6067007415\",\"2\":\"494\"},{\"1\":\"6067007416\",\"2\":\"494\"},{\"1\":\"6067007417\",\"2\":\"494\"},{\"1\":\"6067007421\",\"2\":\"494\"},{\"1\":\"6067007422\",\"2\":\"494\"},{\"1\":\"6067007423\",\"2\":\"494\"},{\"1\":\"6067007424\",\"2\":\"494\"},{\"1\":\"6067007426\",\"2\":\"494\"},{\"1\":\"6067007427\",\"2\":\"494\"},{\"1\":\"6067007428\",\"2\":\"494\"},{\"1\":\"6067007429\",\"2\":\"494\"},{\"1\":\"6067007430\",\"2\":\"494\"},{\"1\":\"6067007431\",\"2\":\"494\"},{\"1\":\"6067007432\",\"2\":\"494\"},{\"1\":\"6067007433\",\"2\":\"494\"},{\"1\":\"6067007501\",\"2\":\"494\"},{\"1\":\"6067007503\",\"2\":\"494\"},{\"1\":\"6067007504\",\"2\":\"494\"},{\"1\":\"6067007601\",\"2\":\"494\"},{\"1\":\"6067007602\",\"2\":\"494\"},{\"1\":\"6067007701\",\"2\":\"494\"},{\"1\":\"6067007702\",\"2\":\"494\"},{\"1\":\"6067007801\",\"2\":\"494\"},{\"1\":\"6067007802\",\"2\":\"494\"},{\"1\":\"6067007903\",\"2\":\"494\"},{\"1\":\"6067007904\",\"2\":\"494\"},{\"1\":\"6067007905\",\"2\":\"494\"},{\"1\":\"6067007906\",\"2\":\"494\"},{\"1\":\"6067008005\",\"2\":\"494\"},{\"1\":\"6067008006\",\"2\":\"494\"},{\"1\":\"6067008007\",\"2\":\"494\"},{\"1\":\"6067008008\",\"2\":\"494\"},{\"1\":\"6067008009\",\"2\":\"494\"},{\"1\":\"6067008010\",\"2\":\"494\"},{\"1\":\"6067008111\",\"2\":\"494\"},{\"1\":\"6067008113\",\"2\":\"494\"},{\"1\":\"6067008117\",\"2\":\"494\"},{\"1\":\"6067008119\",\"2\":\"494\"},{\"1\":\"6067008120\",\"2\":\"494\"},{\"1\":\"6067008122\",\"2\":\"494\"},{\"1\":\"6067008124\",\"2\":\"494\"},{\"1\":\"6067008125\",\"2\":\"494\"},{\"1\":\"6067008127\",\"2\":\"494\"},{\"1\":\"6067008128\",\"2\":\"494\"},{\"1\":\"6067008129\",\"2\":\"494\"},{\"1\":\"6067008130\",\"2\":\"494\"},{\"1\":\"6067008131\",\"2\":\"494\"},{\"1\":\"6067008132\",\"2\":\"494\"},{\"1\":\"6067008133\",\"2\":\"494\"},{\"1\":\"6067008134\",\"2\":\"494\"},{\"1\":\"6067008135\",\"2\":\"494\"},{\"1\":\"6067008136\",\"2\":\"494\"},{\"1\":\"6067008137\",\"2\":\"494\"},{\"1\":\"6067008138\",\"2\":\"494\"},{\"1\":\"6067008139\",\"2\":\"494\"},{\"1\":\"6067008140\",\"2\":\"494\"},{\"1\":\"6067008141\",\"2\":\"494\"},{\"1\":\"6067008142\",\"2\":\"494\"},{\"1\":\"6067008143\",\"2\":\"494\"},{\"1\":\"6067008144\",\"2\":\"494\"},{\"1\":\"6067008145\",\"2\":\"494\"},{\"1\":\"6067008203\",\"2\":\"494\"},{\"1\":\"6067008204\",\"2\":\"494\"},{\"1\":\"6067008206\",\"2\":\"494\"},{\"1\":\"6067008207\",\"2\":\"494\"},{\"1\":\"6067008208\",\"2\":\"494\"},{\"1\":\"6067008209\",\"2\":\"494\"},{\"1\":\"6067008210\",\"2\":\"494\"},{\"1\":\"6067008211\",\"2\":\"494\"},{\"1\":\"6067008402\",\"2\":\"494\"},{\"1\":\"6067008403\",\"2\":\"494\"},{\"1\":\"6067008404\",\"2\":\"494\"},{\"1\":\"6067008501\",\"2\":\"494\"},{\"1\":\"6067008504\",\"2\":\"494\"},{\"1\":\"6067008505\",\"2\":\"494\"},{\"1\":\"6067008506\",\"2\":\"494\"},{\"1\":\"6067008507\",\"2\":\"494\"},{\"1\":\"6067008508\",\"2\":\"494\"},{\"1\":\"6067008509\",\"2\":\"494\"},{\"1\":\"6067008510\",\"2\":\"494\"},{\"1\":\"6067008512\",\"2\":\"494\"},{\"1\":\"6067008513\",\"2\":\"494\"},{\"1\":\"6067008600\",\"2\":\"494\"},{\"1\":\"6067008702\",\"2\":\"494\"},{\"1\":\"6067008703\",\"2\":\"494\"},{\"1\":\"6067008704\",\"2\":\"494\"},{\"1\":\"6067008705\",\"2\":\"494\"},{\"1\":\"6067008801\",\"2\":\"494\"},{\"1\":\"6067008905\",\"2\":\"494\"},{\"1\":\"6067008907\",\"2\":\"494\"},{\"1\":\"6067008908\",\"2\":\"494\"},{\"1\":\"6067008909\",\"2\":\"494\"},{\"1\":\"6067008910\",\"2\":\"494\"},{\"1\":\"6067008911\",\"2\":\"494\"},{\"1\":\"6067008912\",\"2\":\"494\"},{\"1\":\"6067008913\",\"2\":\"494\"},{\"1\":\"6067009004\",\"2\":\"494\"},{\"1\":\"6067009005\",\"2\":\"494\"},{\"1\":\"6067009006\",\"2\":\"494\"},{\"1\":\"6067009007\",\"2\":\"494\"},{\"1\":\"6067009008\",\"2\":\"494\"},{\"1\":\"6067009010\",\"2\":\"494\"},{\"1\":\"6067009011\",\"2\":\"494\"},{\"1\":\"6067009103\",\"2\":\"494\"},{\"1\":\"6067009105\",\"2\":\"494\"},{\"1\":\"6067009106\",\"2\":\"494\"},{\"1\":\"6067009107\",\"2\":\"494\"},{\"1\":\"6067009108\",\"2\":\"494\"},{\"1\":\"6067009109\",\"2\":\"494\"},{\"1\":\"6067009110\",\"2\":\"494\"},{\"1\":\"6067009111\",\"2\":\"494\"},{\"1\":\"6067009112\",\"2\":\"494\"},{\"1\":\"6067009201\",\"2\":\"494\"},{\"1\":\"6067009307\",\"2\":\"494\"},{\"1\":\"6067009308\",\"2\":\"494\"},{\"1\":\"6067009309\",\"2\":\"494\"},{\"1\":\"6067009310\",\"2\":\"494\"},{\"1\":\"6067009311\",\"2\":\"494\"},{\"1\":\"6067009312\",\"2\":\"494\"},{\"1\":\"6067009314\",\"2\":\"494\"},{\"1\":\"6067009316\",\"2\":\"494\"},{\"1\":\"6067009317\",\"2\":\"494\"},{\"1\":\"6067009318\",\"2\":\"494\"},{\"1\":\"6067009319\",\"2\":\"494\"},{\"1\":\"6067009320\",\"2\":\"494\"},{\"1\":\"6067009321\",\"2\":\"494\"},{\"1\":\"6067009322\",\"2\":\"494\"},{\"1\":\"6067009323\",\"2\":\"494\"},{\"1\":\"6067009324\",\"2\":\"494\"},{\"1\":\"6067009325\",\"2\":\"494\"},{\"1\":\"6067009326\",\"2\":\"494\"},{\"1\":\"6067009328\",\"2\":\"494\"},{\"1\":\"6067009329\",\"2\":\"494\"},{\"1\":\"6067009330\",\"2\":\"494\"},{\"1\":\"6067009331\",\"2\":\"494\"},{\"1\":\"6067009332\",\"2\":\"494\"},{\"1\":\"6067009403\",\"2\":\"494\"},{\"1\":\"6067009404\",\"2\":\"494\"},{\"1\":\"6067009406\",\"2\":\"494\"},{\"1\":\"6067009407\",\"2\":\"494\"},{\"1\":\"6067009408\",\"2\":\"494\"},{\"1\":\"6067009501\",\"2\":\"494\"},{\"1\":\"6067009502\",\"2\":\"494\"},{\"1\":\"6067009503\",\"2\":\"494\"},{\"1\":\"6067009504\",\"2\":\"494\"},{\"1\":\"6067009601\",\"2\":\"494\"},{\"1\":\"6067009606\",\"2\":\"494\"},{\"1\":\"6067009608\",\"2\":\"494\"},{\"1\":\"6067009609\",\"2\":\"494\"},{\"1\":\"6067009610\",\"2\":\"494\"},{\"1\":\"6067009611\",\"2\":\"494\"},{\"1\":\"6067009612\",\"2\":\"494\"},{\"1\":\"6067009614\",\"2\":\"494\"},{\"1\":\"6067009615\",\"2\":\"494\"},{\"1\":\"6067009616\",\"2\":\"494\"},{\"1\":\"6067009617\",\"2\":\"494\"},{\"1\":\"6067009618\",\"2\":\"494\"},{\"1\":\"6067009619\",\"2\":\"494\"},{\"1\":\"6067009622\",\"2\":\"494\"},{\"1\":\"6067009630\",\"2\":\"494\"},{\"1\":\"6067009632\",\"2\":\"494\"},{\"1\":\"6067009633\",\"2\":\"494\"},{\"1\":\"6067009634\",\"2\":\"494\"},{\"1\":\"6067009635\",\"2\":\"494\"},{\"1\":\"6067009636\",\"2\":\"494\"},{\"1\":\"6067009637\",\"2\":\"494\"},{\"1\":\"6067009638\",\"2\":\"494\"},{\"1\":\"6067009639\",\"2\":\"494\"},{\"1\":\"6067009800\",\"2\":\"494\"},{\"1\":\"6067009900\",\"2\":\"494\"},{\"1\":\"6067988300\",\"2\":\"494\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# how many census tracts in Sacramento County\ncalenviro_stations %>% count(`Census Tract`)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Census Tract\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"6067000100\",\"2\":\"494\"},{\"1\":\"6067000200\",\"2\":\"494\"},{\"1\":\"6067000300\",\"2\":\"494\"},{\"1\":\"6067000400\",\"2\":\"494\"},{\"1\":\"6067000500\",\"2\":\"494\"},{\"1\":\"6067000600\",\"2\":\"494\"},{\"1\":\"6067000700\",\"2\":\"494\"},{\"1\":\"6067000800\",\"2\":\"494\"},{\"1\":\"6067001101\",\"2\":\"494\"},{\"1\":\"6067001200\",\"2\":\"494\"},{\"1\":\"6067001300\",\"2\":\"494\"},{\"1\":\"6067001400\",\"2\":\"494\"},{\"1\":\"6067001500\",\"2\":\"494\"},{\"1\":\"6067001600\",\"2\":\"494\"},{\"1\":\"6067001700\",\"2\":\"494\"},{\"1\":\"6067001800\",\"2\":\"494\"},{\"1\":\"6067001900\",\"2\":\"494\"},{\"1\":\"6067002000\",\"2\":\"494\"},{\"1\":\"6067002100\",\"2\":\"494\"},{\"1\":\"6067002200\",\"2\":\"494\"},{\"1\":\"6067002300\",\"2\":\"494\"},{\"1\":\"6067002400\",\"2\":\"494\"},{\"1\":\"6067002500\",\"2\":\"494\"},{\"1\":\"6067002600\",\"2\":\"494\"},{\"1\":\"6067002700\",\"2\":\"494\"},{\"1\":\"6067002800\",\"2\":\"494\"},{\"1\":\"6067002900\",\"2\":\"494\"},{\"1\":\"6067003000\",\"2\":\"494\"},{\"1\":\"6067003101\",\"2\":\"494\"},{\"1\":\"6067003102\",\"2\":\"494\"},{\"1\":\"6067003202\",\"2\":\"494\"},{\"1\":\"6067003203\",\"2\":\"494\"},{\"1\":\"6067003204\",\"2\":\"494\"},{\"1\":\"6067003300\",\"2\":\"494\"},{\"1\":\"6067003400\",\"2\":\"494\"},{\"1\":\"6067003501\",\"2\":\"494\"},{\"1\":\"6067003502\",\"2\":\"494\"},{\"1\":\"6067003600\",\"2\":\"494\"},{\"1\":\"6067003700\",\"2\":\"494\"},{\"1\":\"6067003800\",\"2\":\"494\"},{\"1\":\"6067003900\",\"2\":\"494\"},{\"1\":\"6067004001\",\"2\":\"494\"},{\"1\":\"6067004004\",\"2\":\"494\"},{\"1\":\"6067004005\",\"2\":\"494\"},{\"1\":\"6067004006\",\"2\":\"494\"},{\"1\":\"6067004008\",\"2\":\"494\"},{\"1\":\"6067004009\",\"2\":\"494\"},{\"1\":\"6067004010\",\"2\":\"494\"},{\"1\":\"6067004011\",\"2\":\"494\"},{\"1\":\"6067004012\",\"2\":\"494\"},{\"1\":\"6067004100\",\"2\":\"494\"},{\"1\":\"6067004201\",\"2\":\"494\"},{\"1\":\"6067004202\",\"2\":\"494\"},{\"1\":\"6067004203\",\"2\":\"494\"},{\"1\":\"6067004300\",\"2\":\"494\"},{\"1\":\"6067004401\",\"2\":\"494\"},{\"1\":\"6067004402\",\"2\":\"494\"},{\"1\":\"6067004501\",\"2\":\"494\"},{\"1\":\"6067004502\",\"2\":\"494\"},{\"1\":\"6067004601\",\"2\":\"494\"},{\"1\":\"6067004602\",\"2\":\"494\"},{\"1\":\"6067004701\",\"2\":\"494\"},{\"1\":\"6067004702\",\"2\":\"494\"},{\"1\":\"6067004801\",\"2\":\"494\"},{\"1\":\"6067004802\",\"2\":\"494\"},{\"1\":\"6067004903\",\"2\":\"494\"},{\"1\":\"6067004904\",\"2\":\"494\"},{\"1\":\"6067004905\",\"2\":\"494\"},{\"1\":\"6067004906\",\"2\":\"494\"},{\"1\":\"6067005001\",\"2\":\"494\"},{\"1\":\"6067005002\",\"2\":\"494\"},{\"1\":\"6067005101\",\"2\":\"494\"},{\"1\":\"6067005102\",\"2\":\"494\"},{\"1\":\"6067005201\",\"2\":\"494\"},{\"1\":\"6067005202\",\"2\":\"494\"},{\"1\":\"6067005204\",\"2\":\"494\"},{\"1\":\"6067005205\",\"2\":\"494\"},{\"1\":\"6067005301\",\"2\":\"494\"},{\"1\":\"6067005402\",\"2\":\"494\"},{\"1\":\"6067005403\",\"2\":\"494\"},{\"1\":\"6067005404\",\"2\":\"494\"},{\"1\":\"6067005502\",\"2\":\"494\"},{\"1\":\"6067005505\",\"2\":\"494\"},{\"1\":\"6067005506\",\"2\":\"494\"},{\"1\":\"6067005508\",\"2\":\"494\"},{\"1\":\"6067005509\",\"2\":\"494\"},{\"1\":\"6067005510\",\"2\":\"494\"},{\"1\":\"6067005601\",\"2\":\"494\"},{\"1\":\"6067005605\",\"2\":\"494\"},{\"1\":\"6067005606\",\"2\":\"494\"},{\"1\":\"6067005701\",\"2\":\"494\"},{\"1\":\"6067005702\",\"2\":\"494\"},{\"1\":\"6067005801\",\"2\":\"494\"},{\"1\":\"6067005803\",\"2\":\"494\"},{\"1\":\"6067005804\",\"2\":\"494\"},{\"1\":\"6067005901\",\"2\":\"494\"},{\"1\":\"6067005903\",\"2\":\"494\"},{\"1\":\"6067005904\",\"2\":\"494\"},{\"1\":\"6067006002\",\"2\":\"494\"},{\"1\":\"6067006003\",\"2\":\"494\"},{\"1\":\"6067006004\",\"2\":\"494\"},{\"1\":\"6067006101\",\"2\":\"494\"},{\"1\":\"6067006102\",\"2\":\"494\"},{\"1\":\"6067006201\",\"2\":\"494\"},{\"1\":\"6067006202\",\"2\":\"494\"},{\"1\":\"6067006300\",\"2\":\"494\"},{\"1\":\"6067006400\",\"2\":\"494\"},{\"1\":\"6067006500\",\"2\":\"494\"},{\"1\":\"6067006600\",\"2\":\"494\"},{\"1\":\"6067006701\",\"2\":\"494\"},{\"1\":\"6067006702\",\"2\":\"494\"},{\"1\":\"6067006800\",\"2\":\"494\"},{\"1\":\"6067006900\",\"2\":\"494\"},{\"1\":\"6067007001\",\"2\":\"494\"},{\"1\":\"6067007004\",\"2\":\"494\"},{\"1\":\"6067007007\",\"2\":\"494\"},{\"1\":\"6067007010\",\"2\":\"494\"},{\"1\":\"6067007011\",\"2\":\"494\"},{\"1\":\"6067007012\",\"2\":\"494\"},{\"1\":\"6067007013\",\"2\":\"494\"},{\"1\":\"6067007014\",\"2\":\"494\"},{\"1\":\"6067007015\",\"2\":\"494\"},{\"1\":\"6067007016\",\"2\":\"494\"},{\"1\":\"6067007017\",\"2\":\"494\"},{\"1\":\"6067007018\",\"2\":\"494\"},{\"1\":\"6067007019\",\"2\":\"494\"},{\"1\":\"6067007020\",\"2\":\"494\"},{\"1\":\"6067007101\",\"2\":\"494\"},{\"1\":\"6067007102\",\"2\":\"494\"},{\"1\":\"6067007103\",\"2\":\"494\"},{\"1\":\"6067007104\",\"2\":\"494\"},{\"1\":\"6067007105\",\"2\":\"494\"},{\"1\":\"6067007106\",\"2\":\"494\"},{\"1\":\"6067007107\",\"2\":\"494\"},{\"1\":\"6067007202\",\"2\":\"494\"},{\"1\":\"6067007204\",\"2\":\"494\"},{\"1\":\"6067007206\",\"2\":\"494\"},{\"1\":\"6067007207\",\"2\":\"494\"},{\"1\":\"6067007208\",\"2\":\"494\"},{\"1\":\"6067007209\",\"2\":\"494\"},{\"1\":\"6067007301\",\"2\":\"494\"},{\"1\":\"6067007402\",\"2\":\"494\"},{\"1\":\"6067007403\",\"2\":\"494\"},{\"1\":\"6067007406\",\"2\":\"494\"},{\"1\":\"6067007413\",\"2\":\"494\"},{\"1\":\"6067007414\",\"2\":\"494\"},{\"1\":\"6067007415\",\"2\":\"494\"},{\"1\":\"6067007416\",\"2\":\"494\"},{\"1\":\"6067007417\",\"2\":\"494\"},{\"1\":\"6067007421\",\"2\":\"494\"},{\"1\":\"6067007422\",\"2\":\"494\"},{\"1\":\"6067007423\",\"2\":\"494\"},{\"1\":\"6067007424\",\"2\":\"494\"},{\"1\":\"6067007426\",\"2\":\"494\"},{\"1\":\"6067007427\",\"2\":\"494\"},{\"1\":\"6067007428\",\"2\":\"494\"},{\"1\":\"6067007429\",\"2\":\"494\"},{\"1\":\"6067007430\",\"2\":\"494\"},{\"1\":\"6067007431\",\"2\":\"494\"},{\"1\":\"6067007432\",\"2\":\"494\"},{\"1\":\"6067007433\",\"2\":\"494\"},{\"1\":\"6067007501\",\"2\":\"494\"},{\"1\":\"6067007503\",\"2\":\"494\"},{\"1\":\"6067007504\",\"2\":\"494\"},{\"1\":\"6067007601\",\"2\":\"494\"},{\"1\":\"6067007602\",\"2\":\"494\"},{\"1\":\"6067007701\",\"2\":\"494\"},{\"1\":\"6067007702\",\"2\":\"494\"},{\"1\":\"6067007801\",\"2\":\"494\"},{\"1\":\"6067007802\",\"2\":\"494\"},{\"1\":\"6067007903\",\"2\":\"494\"},{\"1\":\"6067007904\",\"2\":\"494\"},{\"1\":\"6067007905\",\"2\":\"494\"},{\"1\":\"6067007906\",\"2\":\"494\"},{\"1\":\"6067008005\",\"2\":\"494\"},{\"1\":\"6067008006\",\"2\":\"494\"},{\"1\":\"6067008007\",\"2\":\"494\"},{\"1\":\"6067008008\",\"2\":\"494\"},{\"1\":\"6067008009\",\"2\":\"494\"},{\"1\":\"6067008010\",\"2\":\"494\"},{\"1\":\"6067008111\",\"2\":\"494\"},{\"1\":\"6067008113\",\"2\":\"494\"},{\"1\":\"6067008117\",\"2\":\"494\"},{\"1\":\"6067008119\",\"2\":\"494\"},{\"1\":\"6067008120\",\"2\":\"494\"},{\"1\":\"6067008122\",\"2\":\"494\"},{\"1\":\"6067008124\",\"2\":\"494\"},{\"1\":\"6067008125\",\"2\":\"494\"},{\"1\":\"6067008127\",\"2\":\"494\"},{\"1\":\"6067008128\",\"2\":\"494\"},{\"1\":\"6067008129\",\"2\":\"494\"},{\"1\":\"6067008130\",\"2\":\"494\"},{\"1\":\"6067008131\",\"2\":\"494\"},{\"1\":\"6067008132\",\"2\":\"494\"},{\"1\":\"6067008133\",\"2\":\"494\"},{\"1\":\"6067008134\",\"2\":\"494\"},{\"1\":\"6067008135\",\"2\":\"494\"},{\"1\":\"6067008136\",\"2\":\"494\"},{\"1\":\"6067008137\",\"2\":\"494\"},{\"1\":\"6067008138\",\"2\":\"494\"},{\"1\":\"6067008139\",\"2\":\"494\"},{\"1\":\"6067008140\",\"2\":\"494\"},{\"1\":\"6067008141\",\"2\":\"494\"},{\"1\":\"6067008142\",\"2\":\"494\"},{\"1\":\"6067008143\",\"2\":\"494\"},{\"1\":\"6067008144\",\"2\":\"494\"},{\"1\":\"6067008145\",\"2\":\"494\"},{\"1\":\"6067008203\",\"2\":\"494\"},{\"1\":\"6067008204\",\"2\":\"494\"},{\"1\":\"6067008206\",\"2\":\"494\"},{\"1\":\"6067008207\",\"2\":\"494\"},{\"1\":\"6067008208\",\"2\":\"494\"},{\"1\":\"6067008209\",\"2\":\"494\"},{\"1\":\"6067008210\",\"2\":\"494\"},{\"1\":\"6067008211\",\"2\":\"494\"},{\"1\":\"6067008402\",\"2\":\"494\"},{\"1\":\"6067008403\",\"2\":\"494\"},{\"1\":\"6067008404\",\"2\":\"494\"},{\"1\":\"6067008501\",\"2\":\"494\"},{\"1\":\"6067008504\",\"2\":\"494\"},{\"1\":\"6067008505\",\"2\":\"494\"},{\"1\":\"6067008506\",\"2\":\"494\"},{\"1\":\"6067008507\",\"2\":\"494\"},{\"1\":\"6067008508\",\"2\":\"494\"},{\"1\":\"6067008509\",\"2\":\"494\"},{\"1\":\"6067008510\",\"2\":\"494\"},{\"1\":\"6067008512\",\"2\":\"494\"},{\"1\":\"6067008513\",\"2\":\"494\"},{\"1\":\"6067008600\",\"2\":\"494\"},{\"1\":\"6067008702\",\"2\":\"494\"},{\"1\":\"6067008703\",\"2\":\"494\"},{\"1\":\"6067008704\",\"2\":\"494\"},{\"1\":\"6067008705\",\"2\":\"494\"},{\"1\":\"6067008801\",\"2\":\"494\"},{\"1\":\"6067008905\",\"2\":\"494\"},{\"1\":\"6067008907\",\"2\":\"494\"},{\"1\":\"6067008908\",\"2\":\"494\"},{\"1\":\"6067008909\",\"2\":\"494\"},{\"1\":\"6067008910\",\"2\":\"494\"},{\"1\":\"6067008911\",\"2\":\"494\"},{\"1\":\"6067008912\",\"2\":\"494\"},{\"1\":\"6067008913\",\"2\":\"494\"},{\"1\":\"6067009004\",\"2\":\"494\"},{\"1\":\"6067009005\",\"2\":\"494\"},{\"1\":\"6067009006\",\"2\":\"494\"},{\"1\":\"6067009007\",\"2\":\"494\"},{\"1\":\"6067009008\",\"2\":\"494\"},{\"1\":\"6067009010\",\"2\":\"494\"},{\"1\":\"6067009011\",\"2\":\"494\"},{\"1\":\"6067009103\",\"2\":\"494\"},{\"1\":\"6067009105\",\"2\":\"494\"},{\"1\":\"6067009106\",\"2\":\"494\"},{\"1\":\"6067009107\",\"2\":\"494\"},{\"1\":\"6067009108\",\"2\":\"494\"},{\"1\":\"6067009109\",\"2\":\"494\"},{\"1\":\"6067009110\",\"2\":\"494\"},{\"1\":\"6067009111\",\"2\":\"494\"},{\"1\":\"6067009112\",\"2\":\"494\"},{\"1\":\"6067009201\",\"2\":\"494\"},{\"1\":\"6067009307\",\"2\":\"494\"},{\"1\":\"6067009308\",\"2\":\"494\"},{\"1\":\"6067009309\",\"2\":\"494\"},{\"1\":\"6067009310\",\"2\":\"494\"},{\"1\":\"6067009311\",\"2\":\"494\"},{\"1\":\"6067009312\",\"2\":\"494\"},{\"1\":\"6067009314\",\"2\":\"494\"},{\"1\":\"6067009316\",\"2\":\"494\"},{\"1\":\"6067009317\",\"2\":\"494\"},{\"1\":\"6067009318\",\"2\":\"494\"},{\"1\":\"6067009319\",\"2\":\"494\"},{\"1\":\"6067009320\",\"2\":\"494\"},{\"1\":\"6067009321\",\"2\":\"494\"},{\"1\":\"6067009322\",\"2\":\"494\"},{\"1\":\"6067009323\",\"2\":\"494\"},{\"1\":\"6067009324\",\"2\":\"494\"},{\"1\":\"6067009325\",\"2\":\"494\"},{\"1\":\"6067009326\",\"2\":\"494\"},{\"1\":\"6067009328\",\"2\":\"494\"},{\"1\":\"6067009329\",\"2\":\"494\"},{\"1\":\"6067009330\",\"2\":\"494\"},{\"1\":\"6067009331\",\"2\":\"494\"},{\"1\":\"6067009332\",\"2\":\"494\"},{\"1\":\"6067009403\",\"2\":\"494\"},{\"1\":\"6067009404\",\"2\":\"494\"},{\"1\":\"6067009406\",\"2\":\"494\"},{\"1\":\"6067009407\",\"2\":\"494\"},{\"1\":\"6067009408\",\"2\":\"494\"},{\"1\":\"6067009501\",\"2\":\"494\"},{\"1\":\"6067009502\",\"2\":\"494\"},{\"1\":\"6067009503\",\"2\":\"494\"},{\"1\":\"6067009504\",\"2\":\"494\"},{\"1\":\"6067009601\",\"2\":\"494\"},{\"1\":\"6067009606\",\"2\":\"494\"},{\"1\":\"6067009608\",\"2\":\"494\"},{\"1\":\"6067009609\",\"2\":\"494\"},{\"1\":\"6067009610\",\"2\":\"494\"},{\"1\":\"6067009611\",\"2\":\"494\"},{\"1\":\"6067009612\",\"2\":\"494\"},{\"1\":\"6067009614\",\"2\":\"494\"},{\"1\":\"6067009615\",\"2\":\"494\"},{\"1\":\"6067009616\",\"2\":\"494\"},{\"1\":\"6067009617\",\"2\":\"494\"},{\"1\":\"6067009618\",\"2\":\"494\"},{\"1\":\"6067009619\",\"2\":\"494\"},{\"1\":\"6067009622\",\"2\":\"494\"},{\"1\":\"6067009630\",\"2\":\"494\"},{\"1\":\"6067009632\",\"2\":\"494\"},{\"1\":\"6067009633\",\"2\":\"494\"},{\"1\":\"6067009634\",\"2\":\"494\"},{\"1\":\"6067009635\",\"2\":\"494\"},{\"1\":\"6067009636\",\"2\":\"494\"},{\"1\":\"6067009637\",\"2\":\"494\"},{\"1\":\"6067009638\",\"2\":\"494\"},{\"1\":\"6067009639\",\"2\":\"494\"},{\"1\":\"6067009800\",\"2\":\"494\"},{\"1\":\"6067009900\",\"2\":\"494\"},{\"1\":\"6067988300\",\"2\":\"494\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\nSo there are 317 census tracts in Sacramento County, and 494 unique groundwater stations. If we multiply 317 * 494, we get the number of observations in our dataset (`n = 156,598`). So, it seems every single station is being joined to every single census tract...that's because we only have county to join on.\n\nFor these sorts of operations, we actually want a more spatially explicit join to reduce this sort of duplication. Thankfully we've done this already. Let's grab this data now so we can use it to make a better join of the data. [Download it here](), and see the [spatial mapmaking module](m_intro_mapmaking.qmd) to see more on spatial joins. Let's join our full joined Sacramento County groundwater dataset from earlier using the census tracts instead of county.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# can use URL here too: \nxwalk <- read_csv(\"data/calenviroscreen/sac_county_crosswalk_to_gw_stations.csv\") %>% \n  # filter to just columns we need\n  select(SITE_CODE, tract)\n\n# join with station data...adding \"tract\" to dataframe\nsac_stations_w_tracts <- left_join(sac_stations, xwalk)\n\n# now join to CalEnviroScreen data\nsac_station_calenviro_by_tracts <- left_join(sac_stations_w_tracts, calenviro,\n                                             by = c(\"tract\" = \"Census Tract\"))\n\n# check dim\ndim(sac_station_calenviro_by_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 495  72\n```\n\n\n:::\n:::\n\n\n\n\nOk, so what happened? We used an intermediate table (`xwalk`) to crosswalk using a finer resolution join for our stations. So now each census tract is associated with a specific groundwater station in Sacramento County, based on a spatial join of the CalEnviroScreen data with the stations data.\n\nLet's close the loop, and join the station-calenviroscreen data back to our `gw_perf` and `gw_measurement` data so we have one single dataset for Sacramento County!\n\n<!-- can add section on pivot_longer/wider here later -->\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsac_gw_all <- left_join(sac_station_calenviro_by_tracts, gw_perf) %>% \n  left_join(., gw_measurements)\n\n# lets move the CalEnviroScreen variables to the end\nsac_gw_all <- sac_gw_all %>% \n  select(STN_ID:WCR_NO, TOP_PRF:COOP_ORG_NAME, tract:`Pop. Char. Pctl`)\n```\n:::\n\n\n\n\n## Save it Out!\n\nRemember how to do this? Let's save this using an R specific format, `.rds`, because it will retain the formatting and allow us to import/read in the data using whatever name we prefer. Here we'll use the `write_rds()` function from the `{readr}` package (part of the `{tidyverse}`). \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# remember to use a relative path!\nwrite_rds(sac_gw_all, file = \"data/sacramento_gw_data_w_calenviro.rds\")\n```\n:::\n\n\n\n\n\n<br>  \n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}