---
title: "Parameterized reports"
description: | 
   description
output: 
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE, purl=FALSE, message=FALSE}

library(knitr)
library(glue)
library(here)

```

::: {.obj}
**Learning objectives**

-   Extend functional programming skills to automate `.Rmd` reports  
-   Understand the available types of reports provided by `{rmarkdown}`  
:::

Analyses typically lead to figures, tables, and a narrative interpreting these information. The [`{rmarkdown}`](https://rmarkdown.rstudio.com/) package provides `R` users with a standardized approach for turning `R` analyses into reports, documents, presentations, dashboards, and websites. In this module, we assume familiarity with `{rmarkdown}`, and extend the previous modules on iteration, functional programming, and reproducible workflows to demonstrate how to iterate over reports.

<aside>
If needed, review the [introduction to `{rmarkdown}`](../intro/m_intro_Rmarkdown.html).
</aside>

Let's assume that we want to generate a report on groundwater level trends for a set of counties. 


## 



## Additional Resources



<br>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<a href="m_reproducible_workflows.html" class="btn btn-secondary" style="float: left">Previous module:<br>Reproducible Workflows</a> <a href="m_advanced_spatial.html" class="btn btn-secondary" style="float: right;">Next module:<br>Advanced spatial</a>

